### PR TITLE
Remove cf and batch_scan from examples/raw.rs

### PR DESCRIPTION
**Pull request by sunxiaoguang**

### CODE REVIEW

**Comment by siddontang** [comment]
why removing batch_scan?

**Comment by sunxiaoguang** [comment]
> why removing batch_scan?

It's not implemented at client side yet, like cf. They will be back to examples when prerequisites are satisfied.

**Comment by siddontang** [comment]
@Hoverbear 
CI failed

**Comment by siddontang** [comment]
I will merge the PR forcibly because it is not related to the CI failure.
PTAL investigate this @Hoverbear

**Pull request merged**
