### PR TITLE
Improve ergonomics

### PR DESCRIPTION
**Pull request by andylokandy**
This PR contains two changes:

1. move `key_only` from client to scan.
2. move `pd_endpoints` from config to client.

IMO, these two are a bit confusing and not so idiomatic to rust.

### CODE REVIEW

**Review by nrc — COMMENTED** [review]
I like the change moving pd endpoints from config to client. I'm not sure about the change to key_only. The philosophy with the design is that options which are not frequently used (key_only, cf) should not have to be specified since that causes boilerplate on every call. What are your thoughts on moving it?

**Comment by ekexium** [comment]
How about using two different methods `scan` and `scan_keys`?

**Comment by andylokandy** [comment]
@nrc Not similar to the cf, the key_only only affects scans. @ekexium 's solution seems better.

Ps: the ultimate solution is named/default arguments... no idea why rust doesn't have.

**Comment by andylokandy** [comment]
One more reason for the key_only is that we can't scan key_only and kvpair in one transaction.

**Comment by andylokandy** [comment]
@ekexium PTAL

**Comment by ekexium** [comment]
lgtm

**Comment by nrc** [comment]
OK, I like the scan/scan_keys solution. I am a bit wary of having lots of subtly different functions, but this one seems fine.

**Pull request merged**
