### PR TITLE
Extract out some modules from lib.rs

### PR DESCRIPTION
**Pull request by nrc**
And bring license headers inline with TiKV

PTAL @Hoverbear (easier to review each commit at a time)

### CODE REVIEW

**Comment by nrc** [comment]
Guess this is failing CI until #49 is merged in

**Comment by Hoverbear** [comment]
Let's have a try now!

**Comment by nrc** [comment]
All checks passed \o/

@Hoverbear PTAL

**Comment by nrc** [comment]
ping @ice1000 for review please

**Pull request merged**
