### PR TITLE
Fix region cache update error when handle not leader

### PR DESCRIPTION
**Pull request by yongman**
The `region cache map` may be updated by concurrency when do `handle_region_error`, this may result in a lot of `EntrynotFoundInRegionCache` error. 
We should check if region entry exists, ignore update leader if entry is none. The entry cache will be filled up in the next get region reqeust.

### CODE REVIEW

**Comment by yongman** [comment]
@ekexium The ci check failure has no relation with this pr, can we fix it in another pr?

**Comment by yongman** [comment]
CI clippy failure is the new feature and have an issue not resolved https://github.com/rust-lang/rust-clippy/issues/8867 in nightly version.

**Comment by iosmanthus** [comment]
Rest LGTM, please fix the CI and clippy.

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
