### PR TITLE
Batch split for prewrite and commit requests 

### PR DESCRIPTION
**Pull request by akoshchiy**
ref #369
Still in progress, here is draft api for splitting/merging requests into batches (RawBatchPutRequest as example). 
After approve i will finish for the rest.

### CODE REVIEW

**Comment by roguepnz** [comment]
PTAL @ekexium

**Comment by ekexium** [comment]
Hey thank you for the work! 
I think we'd better not split a raw request which could make it non-atomic.
I guess supporting prewrite and commit requests in transactional API would be enough for us.
And we need a test to verify that it works

**Comment by roguepnz** [comment]
@ekexium Since we don't need reusable api for batches, is it ok to implement batching for prewrite/commit requests directly in Shardable trait implementation? As an example, if we have two regions and two batches inside each region, shards() method will return four "shards".
So, it won't be necessary to merge batch responses, and other logic in request pipeline will be untouched.

**Comment by ekexium** [comment]
> @ekexium Since we don't need reusable api for batches, is it ok to implement batching for prewrite/commit requests directly in Shardable trait implementation? As an example, if we have two regions and two batches inside each region, shards() method will return four "shards". So, it won't be necessary to merge batch responses, and other logic in request pipeline will be untouched.

Yes we can

**Comment by roguepnz** [comment]
@ekexium PTAL.
Added raft-entry-max-size to the config to be able to test with small amount of data.

**Review by ekexium — APPROVED** [review]

**Pull request merged**
