### PR TITLE
ci: remove doc action and travis config

### PR DESCRIPTION
**Pull request by ekexium**
Motivation:
1. tikv.dev is not actively maintained. And the stable document is now available at docs.rs.
2. We have migrated CI to GitHub Actions.

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
lgtm

**Comment by hi-rustin** [comment]
> @hi-rustin, Thanks for your review. The bot only counts LGTMs from Reviewers and higher roles, but you're still welcome to leave your comments. See the corresponding SIG page for more information. Related SIG: [transaction](https://github.com/tikv/community/tree/master/sig/transaction)([slack](https://slack.tidb.io/invite?team=tikv-wg&channel=sig-transaction&ref=github)).

Maybe we can remove this robot that looks like we're not using it!

**Review by hi-rustin — APPROVED** [review]

**Comment by ekexium** [comment]
ping @andylokandy

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
