### PR TITLE
Implement a unit test by mocking lower level clients

### PR DESCRIPTION
**Pull request by nrc**
This needed a lot of refactoring. I think that improves things though.

### CODE REVIEW

**Comment by nrc** [comment]
PTAL @Hoverbear @brson

**Comment by brson** [comment]
And I'm guessing there is not true mocking here right? The RetryClient remains the production PdClient?

**Comment by brson** [comment]
All the `pub (in foo)` annotations give me a bad smell. Better than pure pub everywhere, but it indicates disorganization to me. Better for everything to be daggy, such that mods could be crates later. Not something to fix here though.

**Comment by nrc** [comment]
>  Is PdClient the only thing that needs to be mocked to enable unit testing? 

No, it is just the first step, I suspect we will need to be able to mock each layer of client to test the layer above.

>  It seems like the KvClient / TikvClient (don't know the difference) could be usefully mocked as well

Yes, for sure.

> And I'm guessing there is not true mocking here right? The RetryClient remains the production PdClient?

I'm not sure what you mean. Yes, the `RetryClient` is the production client and `MockPdClient` is the mock client.

> All the pub (in foo) annotations give me a bad smell

Yeah, I'm not a fan. I'll try and get rid of them in the future...

**Comment by brson** [comment]
> I'm not sure what you mean. Yes, the `RetryClient` is the production client and `MockPdClient` is the mock client.

Oh, I must have missed `MockPdClient` behind one of the big diff load links.

**Pull request merged**
